name: CI

'on':
    schedule:
      - cron: '30 4 * * 1'  # Every Monday at 4:30
    pull_request:
    push:
        branches:
          - master

env:
    UBSAN_OPTIONS: print_stacktrace=1
    ASAN_OPTIONS: detect_odr_violation=2

jobs:
    posix:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: ubuntu-24.04
                    cpp_compiler: g++

        name: '${{matrix.os}}: ${{matrix.cpp_compiler}}'
        runs-on: ${{matrix.os}}

        steps:
          - uses: actions/checkout@v4

          - name: Install deps
            run: |
                sudo apt update
                sudo apt install --allow-downgrades -y git gcc g++ cmake clang libc++-dev

          - name: Run CMake
            run: |
                mkdir build
                cd build
                cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}} ..

          - name: Build
            run: |
                cd build
                VERBOSE=1 make -j2

          - name: Test
            run: |
                cd build
                ./cpp_fast

          - name: Coverage
            run: |
                cd build
                bash <(curl -s https://codecov.io/bash) -f '!*benchmark*'

